services:
  web_sley:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - app_network
    container_name: angular_container

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network
    depends_on:
      - web_sley  # Aquí depende del servicio `web_sley`

networks:
  app_network:
    driver: bridge
